### ISSUE TITLE
Button Roles

### ISSUE THREAD

**Issue by kieranperk** [Manumission247/ModManager#17]
**Is your feature request related to a problem? Please describe.**
As reaction role bots have been round for a long time, I think modmanager would benefit from an updated system. 

**Describe the solution you'd like**
I'm not saying just delete the old reaction role system, but I think by adding the option to do reactions through buttons would be cool! It Allows users to completely customize their role systems with the different coloured buttons, emoji buttons and also by adding text as well!

**Describe alternatives you've considered**
Urm, there aren't any alternatives...

**Additional context**
I think I've described it pretty well.

**Comment by EddiesLife247** [comment]
This is being implemented into v4.

**Comment by EddiesLife247** [comment]
Issue has been implemented into V4 Release
